"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import environ
import os
from django.utils.translation import gettext_lazy as _

from pathlib import Path

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-i9ik(w*m4l!@k$8r*ss3-2!mcl6#z8@%s16ohbadz-5fm%1i!5'
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# False if not in os.environ because of casting above
DEBUG = env("DEBUG")

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=["Not set in .env file"])

# Fortæller Django at den er bag en reverse proxy (Nginx) der håndterer SSL
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Site info
# Project title displayed in the header
PROJECT_TITLE = env("PROJECT_TITLE")

SITE = env("SITE")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_bootstrap5",
    "core",
    "allauth",
    "allauth.account",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.cprocs.site_info",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LOCALE_PATHS = [
    BASE_DIR / "locale/",
]

LANGUAGES = (
    ("da", _("Danish")),
    ("en", _("English")),
)

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": env("EMAIL_BACKEND"),
        "OPTIONS": {
            "host": env("SP_EMAIL_HOST"),
            "use_tls": env("SP_EMAIL_USE_TLS"),
            "username": env("SP_EMAIL_HOST_USER"),
            "password": env("SP_EMAIL_HOST_PASSWORD"),
        },
    },
}

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
ADMIN_NEW_USER = env.list("ADMIN_NEW_USER", default=[])

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# # Sparkpost email
# EMAIL_HOST = env.str("SP_EMAIL_HOST")
# EMAIL_PORT = env.str("SP_EMAIL_PORT")
# EMAIL_HOST_USER = env.str("SP_EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = env.str("SP_EMAIL_HOST_PASSWORD")
# EMAIL_USE_TLS = env.bool("SP_EMAIL_USE_TLS")

AUTH_USER_MODEL = "core.User"

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]
ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_SIGNUP_FORM_CLASS = "core.forms.CustomSignupForm"
ACCOUNT_ADAPTER = 'core.adapter.ApprovalAccountAdapter'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False  # <--- VIGTIGT: Forhindrer autologin ved klik på link
# ACCOUNT_RATE_LIMITS = env("ACCOUNT_RATE_LIMITS", default="Off")
ACCOUNT_RATE_LIMITS = env("ACCOUNT_RATE_LIMITS", default="5/m")  # <--- VIGTIGT: Forhindrer brute force login

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
